In [2]:
# Importing relavant libraries
import pandas as pd
import numpy as np
from datetime import datetime

In [3]:
# Creating a data frame
# Working with only 10% of the data due to file size
sensorData = pd.read_csv('On-street_Car_Parking_Sensor_Data_-_2020__Jan_-_May_.csv').sample(frac=0.1, random_state=123)

In [4]:
# Identifying the features
print(sensorData.shape)
print(sensorData.dtypes)
sensorData

(1416582, 19)
DeviceId              int64
ArrivalTime          object
DepartureTime        object
DurationMinutes       int64
StreetMarker         object
SignPlateID         float64
Sign                 object
AreaName             object
StreetId              int64
StreetName           object
BetweenStreet1ID      int64
BetweenStreet1       object
BetweenStreet2ID    float64
BetweenStreet2       object
SideOfStreet          int64
SideName             object
BayId                 int64
InViolation           int64
VehiclePresent        int64
dtype: object

,DeviceId,ArrivalTime,DepartureTime,DurationMinutes,StreetMarker,SignPlateID,Sign,AreaName,StreetId,StreetName,BetweenStreet1ID,BetweenStreet1,BetweenStreet2ID,BetweenStreet2,SideOfStreet,SideName,BayId,InViolation,VehiclePresent
5722474,25475,02/28/2020 12:12:20 PM,02/28/2020 12:12:48 PM,0,15141S,660.0,2P M-SUN 7:30AM-11PM,All,822,JOLIMONT STREET,823,JOLIMONT TERRACE,821.0,JOLIMONT ROAD,4,South,8096,0,0
12355225,28134,01/12/2020 12:00:00 AM,01/12/2020 12:39:01 AM,39,6012N,NaN,NaN,Mint,5,A'BECKETT STREET,1428,WILLIAM STREET,1171.0,QUEEN STREET,3,North,3328,0,0
7022345,26111,05/25/2020 10:53:11 PM,05/25/2020 10:53:32 PM,0,C552,NaN,NaN,Regency,647,EXHIBITION STREET,926,LITTLE LONSDALE STREET,894.0,LONSDALE STREET,1,Centre,824,0,0
14148277,29418,05/15/2020 05:35:18 PM,05/15/2020 05:46:34 PM,11,13619W,628.0,P/ 10mins 7.30 -19.30 M-Su,Docklands,998,MERCHANT STREET,123,BOURKE STREET,1458.0,VICTORIA HARBOUR PROMENADE,5,West,6639,0,0
2170146,23583,02/21/2020 03:13:02 PM,02/21/2020 03:13:30 PM,0,4835W,145.0,2P MTR M-SAT 7:30-20:30,Titles,1171,QUEEN STREET,5,A'BECKETT STREET,856.0,LA TROBE STREET,5,West,2892,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7989532,26462,01/24/2020 12:00:00 AM,01/24/2020 12:18:25 AM,18,2219S,NaN,NaN,McKillop,911,LITTLE COLLINS STREET,1171,QUEEN STREET,627.0,ELIZABETH STREET,4,South,1680,0,1
10832033,27298,05/06/2020 06:20:28 AM,05/06/2020 06:45:39 AM,25,1289W,NaN,NaN,Tavistock,1428,WILLIAM STREET,669,FLINDERS LANE,670.0,FLINDERS STREET,5,West,1298,0,0
9798373,27001,01/19/2020 10:30:41 AM,01/19/2020 10:31:24 AM,1,3452N,3.0,1P SUN 7:30-18:30,Titles,926,LITTLE LONSDALE STREET,1171,QUEEN STREET,627.0,ELIZABETH STREET,3,North,2012,0,0
3414968,24337,01/01/2020 04:24:52 AM,01/01/2020 04:25:07 AM,1,1583S,NaN,NaN,Banks,670,FLINDERS STREET,1171,QUEEN STREET,627.0,ELIZABETH STREET,4,South,1400,0,1
11751670,27609,03/23/2020 12:04:35 PM,03/23/2020 12:51:12 PM,47,2890N,80.0,1P MTR M-F 7:30-16:00,Library,894,LONSDALE STREET,1329,SWANSTON STREET,1221.0,RUSSELL STREET,3,North,2324,0,1

In [5]:
# Identifying numeric columns
df_numeric = sensorData.select_dtypes(include=np.number)
numeric_cols = df_numeric.columns.values
print(numeric_cols)

['DeviceId' 'DurationMinutes' 'SignPlateID' 'StreetId' 'BetweenStreet1ID'
 'BetweenStreet2ID' 'SideOfStreet' 'BayId' 'InViolation' 'VehiclePresent']

In [6]:
# Identifying non numeric columns
df_non_numeric = sensorData.select_dtypes(exclude=np.number)
non_numeric_cols = df_non_numeric.columns.values
print(non_numeric_cols)

['ArrivalTime' 'DepartureTime' 'StreetMarker' 'Sign' 'AreaName'
 'StreetName' 'BetweenStreet1' 'BetweenStreet2' 'SideName']

In [7]:
# Converting time stamps into datetime stamps
sensorData['ArrivalTime'] = pd.to_datetime(sensorData['ArrivalTime'])
sensorData['DepartureTime'] = pd.to_datetime(sensorData['DepartureTime'])

In [15]:
# Dropping non-reqired columns
sensorData = sensorData.drop(columns = ['StreetMarker', 'SignPlateID', 'BetweenStreet1ID', 'BetweenStreet1', 'BetweenStreet2ID', 'BetweenStreet2', 'SideOfStreet'])

In [17]:
# Updated data types
sensorData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1416582 entries, 5722474 to 11751670
Data columns (total 12 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   DeviceId         1416582 non-null  int64
 1   ArrivalTime      1416582 non-null  datetime64[ns]
 2   DepartureTime    1416582 non-null  datetime64[ns]
 3   DurationMinutes  1416582 non-null  int64
 4   Sign             917415 non-null   object
 5   AreaName         1412898 non-null  object
 6   StreetId         1416582 non-null  int64
 7   StreetName       1416582 non-null  object
 8   SideName         1416582 non-null  object
 9   BayId            1416582 non-null  int64
 10  InViolation      1416582 non-null  int64
 11  VehiclePresent   1416582 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(4)
memory usage: 172.7+ MB

Questions
1. Busiest street in rush hours?
2. Average parking time for major streets?
3. Areas where most violations occur?
4. Streets with highest average parking time?
5. Which day of the week is busiest?

In [18]:
# Finding streets with most most sensor triggers 
sensorData.groupby(['StreetId', 'StreetName']).size().sort_values(ascending=False)

StreetId  StreetName
894       LONSDALE STREET                 86125
528       COLLINS STREET                  85020
839       KING STREET                     78137
123       BOURKE STREET                   67817
856       LA TROBE STREET                 61289
                                          ...
917       LITTLE DRYBURGH STREET SOUTH      475
1227      SAINT MANGOS LANE                 470
592       DOEPEL WAY                        415
1078      PALMER STREET                     275
1439      WITCHWOOD CLOSE                    67
Length: 122, dtype: int64

## Londsale Street is the most parked street in 2020

In [20]:
# Analysing morning rush hours
dateData = sensorData.set_index("ArrivalTime")
dateData1 = dateData.between_time('06:00:00', '10:00:00')
dateData1.groupby(['StreetId', 'StreetName']).size().sort_values(ascending=False)

StreetId  StreetName
894       LONSDALE STREET      16629
528       COLLINS STREET       15679
16        ALBERT STREET        15080
839       KING STREET          14338
123       BOURKE STREET        13483
                               ...
1227      SAINT MANGOS LANE       88
1405      WATTLE ROAD             84
1078      PALMER STREET           68
592       DOEPEL WAY              67
1439      WITCHWOOD CLOSE         11
Length: 122, dtype: int64

In [21]:
# Analysing afternoon rush hours
dateData2 = dateData.between_time('15:00:00', '17:00:00')
dateData2.groupby(['StreetId', 'StreetName']).size().sort_values(ascending=False)

StreetId  StreetName
894       LONSDALE STREET                 11544
528       COLLINS STREET                  10055
123       BOURKE STREET                    8804
839       KING STREET                      8475
856       LA TROBE STREET                  8172
                                          ...
701       GEORGIANA STREET                   53
1405      WATTLE ROAD                        47
1078      PALMER STREET                      32
917       LITTLE DRYBURGH STREET SOUTH       26
1439      WITCHWOOD CLOSE                     9
Length: 122, dtype: int64

## Londsdale street has the most cars parked on rush hours.

In [23]:
# Dataframe for 3 main streets
ids = [894, 528, 839]
mainStreets = sensorData[sensorData.StreetId.isin(ids)]
mainStreets

,DeviceId,ArrivalTime,DepartureTime,DurationMinutes,Sign,AreaName,StreetId,StreetName,SideName,BayId,InViolation,VehiclePresent
12697749,28199,2020-03-05 08:12:46,2020-03-05 11:14:04,182,2P MTR M-SAT 7:30-20:30,Supreme,894,LONSDALE STREET,Centre,2546,1,1
10687136,27247,2020-01-08 16:10:09,2020-01-08 16:11:46,1,1P MTR M-SAT 7:30-18:30,Hardware,894,LONSDALE STREET,Centre,2494,0,0
7373281,26228,2020-01-06 19:20:05,2020-01-06 19:24:33,4,2P MTR M-SAT 18.30 - 20.30,Supreme,894,LONSDALE STREET,North,2346,0,0
12556782,28188,2020-01-07 15:04:57,2020-01-07 15:05:19,1,1P MTR M-SAT 7:30-18:30,Docklands,528,COLLINS STREET,North,6048,0,1
7795724,26393,2020-01-09 22:29:43,2020-01-09 22:36:21,7,NaN,Hyatt,528,COLLINS STREET,North,1540,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10622343,27245,2020-04-08 16:17:35,2020-04-08 16:17:43,0,1/2P MTR M-SAT 7.30 TO 18.30,Banks,528,COLLINS STREET,North,1597,0,0
10640137,27245,2020-05-12 13:57:29,2020-05-12 13:57:56,0,1/2P MTR M-SAT 7.30 TO 18.30,Banks,528,COLLINS STREET,North,1597,0,1
8745697,26632,2020-02-06 19:39:45,2020-02-06 19:40:03,1,2P MTR M-F 19:00-20:30,Magistrates,839,KING STREET,East,1274,0,1
10567059,27245,2020-05-22 21:28:01,2020-05-22 21:28:33,0,NaN,Banks,528,COLLINS STREET,North,1597,0,0
11751670,27609,2020-03-23 12:04:35,2020-03-23 12:51:12,47,1P MTR M-F 7:30-16:00,Library,894,LONSDALE STREET,North,2324,0,1

In [24]:
# Average parking duration for main streets
mainStreets['DurationMinutes'].mean()

32.19775194358197

# Average time of parking on major streets(Londsdale Street, Kings Street, Collins Street) is 30 minutes.

In [25]:
# Generating total violations by area
areaData = sensorData.groupby("AreaName")['InViolation'].sum()
areaData.sort_values(ascending=False)

AreaName
Docklands          8413
All                3748
Queensberry        3708
Southbank          3030
Titles             2902
Domain             2638
Princes Theatre    2304
Jolimont           1957
Courtney           1938
Regency            1645
East Melbourne     1522
Hardware           1453
Family             1365
McKillop           1212
Supreme            1211
Twin Towers        1168
Magistrates        1135
Windsor            1119
Library            1118
Hyatt              1077
Victoria Market    1076
Mint               1026
West Melbourne     1026
University          904
County              895
Spencer             803
Chinatown           796
The Mac             691
Markilles           641
City Square         580
Banks               572
Rialto              503
RACV                406
Degraves            386
Tavistock           184
Drummond            172
Name: InViolation, dtype: int64

## Docklands has significantly more violations than any other area.

In [26]:
# Highest average parking time by streets
avgTime =  sensorData.groupby(['StreetId', 'StreetName'])['DurationMinutes'].mean()
avgTime.sort_values(ascending=False)

StreetId  StreetName
917       LITTLE DRYBURGH STREET SOUTH    286.576842
13        AIRLIE STREET                   229.242802
1439      WITCHWOOD CLOSE                 226.925373
617       EADES PLACE                     186.379310
1497      VEGEMITE WAY                    184.549517
                                             ...
627       ELIZABETH STREET                 26.482418
1285      SPENCER STREET                   24.880888
641       ERROL STREET                     23.063302
528       COLLINS STREET                   20.037603
1278      SOUTHBANK BOULEVARD              17.404743
Name: DurationMinutes, Length: 122, dtype: float64

 ## LITTLE DRYBURGH STREET SOUTH has highest average parking time that is around 5 hours

In [27]:
# Sorting data by days and counting them
dayData = sensorData['ArrivalTime'].dt.dayofweek
dayData.groupby(dayData.values).size().sort_values(ascending=False)

4    229727
3    227592
2    221555
1    213673
0    198785
5    182032
6    143218
Name: ArrivalTime, dtype: int64

## Friday has the most number of sensor triggers